service: sample-app
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 128
plugins:
  - serverless-offline
functions:
  app-function:
    handler: src/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
